name: BlockEntityLimiter
version: 1.0.0
main: com.yourname.blockentitylimiter.BlockEntityLimiter
api-version: '1.21'
folia-supported: true
author: YourName
description: Limits the amount of block entities that can be placed in a single chunk

commands:
  belimiter:
    description: Main command for BlockEntityLimiter
    usage: /belimiter <reload>
    aliases: [bel, blocklimiter]
    permission: blockentitylimiter.use

permissions:
  blockentitylimiter.use:
    description: Allows use of the main command
    default: true
  blockentitylimiter.reload:
    description: Allows reloading the configuration
    default: op